### ISSUE TITLE
Program is unstable

### ISSUE THREAD

**Issue by KarelPeeters** [jonte/JarJar9#1]
The program has a couple of problems:
1) It crashes when you have to start and it's your first turn. This is the traceback:
http://imgur.com/U63prg9
2) Previously it sometimes failed to display my letters
3) I couldn't place any letters using the program, the command kept saying "invalid word"
4) I keep getting this error whenever I start the program:
 http://imgur.com/Xl5Hm7n

I can't reproduce point 2 & 3, because of point 4.

I hope you can solve these issues, thanks in advance.

**Comment by jonte** [comment]
Hi, 

I've actually not tried running this in a few years. I'm not sure the wordfeud protocol works in the same way it did back when I wrote this (probably not, since you're getting errors). 

I'll see if I have time to try running this myself in a few days. If authentication, and some basic commands still eork

**Comment by jonte** [comment]
Misclick..  If some basic commands still work, I'll see if I can fix so that the software works again, but since this was written a few years ago, a lot may have changed.

**Comment by KarelPeeters** [comment]
I'm happy to hear you're willing take a look. Some stuff still worked so I hope the protocol hasn't changed too much.

I would also like to ask some (weird) questions:
How do/did you manage(d) to learn their protocol?
Why is this repository called "JarJar9"?

**Comment by KarelPeeters** [comment]
Have you had a chance to look at it already? Or is it too difficult to fix?

**Comment by jonte** [comment]
Hi,

I actually forgot about this, but I had a look just now. The protocol had changed slightly (probably to save some bandwidth.. They removed the "last word" field from the JSON response when no word has been played, which caused a crash).

So, anyway, in 7b9215f5f96fe43467f354162f4f109b9fffd06e, I can actually play words against opponents, which is kind of neat :)

May I ask what your interest is in this software? I should warn you that it's not really ready to be used for gaming purposes.. It's all very rudimentary - but I would welcome pull requests if you'd like to improve it.

Could you verify that 7b9215f5f96fe43467f354162f4f109b9fffd06e fixes your issue?

**Comment by jonte** [comment]
Oh, and I just saw your other questions..

As for how I learned the protocol.. Back when I wrote this, the wordfeud client communicated with the server(s) over HTTP (not HTTPS), which meant I could listen to the communication using a simple packet sniffer installed on my phone. These are available in Google Play, and do not require root access. This is probably the easiest way to see the protocol "in action".

I just tried to do the same (to verify that the protocol is unchanged) - but it seems like they've switched to using HTTPS now. It seems like you can get around this by proxying yourself via an android VPN service, and installing a new root CA certificate, and thus decrypt the messages.. This seems possible with apps from Google play (I just tried very quickly, seems to work).

As for the name, this is just a cheeky pick from my side. JarJar9 is the salt used when hashing passwords (IIRC) before sending them to the WF server. I found this by decompiling the class files within the APK.. Basically I downloaded the WF APK to a Linux machine, unpacked the APK (it's basically just an archive), and ran a decompiler on the .class-files within the APK.. You get semi-readable sources from doing this, and through trial-and-error, I found the salt needed to hash my password.

I hope this clears things up - if you have any more questions, I'm happy to help :)

**Comment by KarelPeeters** [comment]
First of all, thanks for taking some time to fix the program and to answer my questions. Very interesting!

I wanted to know how to communicate with the wordfeud servers to try to make something like this myself in Java, when I stumbled upon this program. I've just started learning Python, so submitting pull requests is still far away :)

I tried to run 7b9215f in Python 2.7.10 and it just opened a blank screen, see http://i.imgur.com/uHoExcc.png. I just updated to Windows 10 so I had to reinstall everything. I'm sure it's not an issue with your program, but do you know what could be the problem?

I'll be away the next week or so, so sorry if my reactions are a bit delayed...

**Comment by KarelPeeters** [comment]
Misclicked as well...

**Comment by jonte** [comment]
Do you have any games currently in progress? It's not supported to initiate new games (that's something you could add if you'd like). 

Could you post your terminal output? Just make sure it doesn't contain any passwords or such.

**Comment by KarelPeeters** [comment]
Yes, I forgot to start a game manually using the app. Thanks!

I'll try to add that when I'm experienced enough in python.

**Comment by jonte** [comment]
Great, then I'll close this issue. I'm happy to accept "beginner level" code and fix it before merging, as a learning experience, If you'd like.

Please open another issue if needed.
